#-------------------------------
# Site Settings
title: Pivoting Life
description: Your podcast station about alternative careers and ventures in the sciences. Here, we talk to people who left well-trodden paths and made bold decisions.
logo: "/images/logo.svg" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo-dark.svg"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Podcast"
      url: "/podcast/"
    - title: "About us"
      url: "/about-us/"
    - title: "Guests"
      url: "/guests/"
    - title: "Contact us"
      url: "/contact-us/"

# Call to action button
cta_button:
  enable: false
  cta_button_link: '/contact/'
  cta_button_text: Get in touch


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Pivoting Life
  hero_description: You podcast station about alternative careers and ventures in the sciences. Here, we talk to people who left well-trodden paths and made <strong>bold decisions</strong>.

#-------------------------------
# Tags Section Settings
tags_section:
  enable: false
  number_posts: 3 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
  number_columns: 3 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.
  tags:
    - tag: "blog"
    - tag: "episode"

# You can add many tag sections to the homepage; each section will show the recent posts by the tag.


#-------------------------------
# Authors Section Settings
authors_section:
  enable: true
  section_title: Meet our team

guests_section:
  enable: true
  section_title: Meet our guests


#-------------------------------
# Footer Settings
footer_description: Don't panic, pivot!


# Social Links
social:
#- {icon: "linkedin", link: "https://www.linkedin.com"}
- {icon: "github", link: "https://github.com/PivotingLife/website"}
#- {icon: "twitter", link: "https://twitter.com"}
#- {icon: "facebook", link: "https://facebook.com"}
#- {icon: "codepen", link: "https://codepen.io"}
#- {icon: "pinterest", link: "https://pinterest.com"}
#- {icon: "youtube", link: "https://youtube.com"}


# Example of adding a new link to the footer - {icon: "instagram", link: "https://instagram.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: false
  mailchimp_title: Get interesting news
  mailchimp_description: Subscribe to our newsletter and weâ€™ll send you the emails of latest posts.
  mailchimp_identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe


#-------------------------------
# Contact Settings
contact:
  email: pivotinglife@icb.uni-due.de # Add your form_id
  description: We'd love to hear from you! Whether you're interested in becoming a writer for our blog or a guest speaker on our podcast, have questions about our platform, or just want to say hello, please don't hesitate to get in touch. Your feedback and inquiries are important to us.  # Add a description of your form

# NOTE
# Danto theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier:  # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id